spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  datasource:
    url: jdbc:mysql://localhost:3306/sponet
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf3:
    decoupled-logic: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  servlet:
    multipart:
      enabled: true # 파일 업로드 기능 여부
      location: C:/HK/PROJECT/upload/pre-image # 파일 임시 저장 경로
      max-request-size: 30MB # 한 번에 최대 업로드 가능 용량
      max-file-size: 10MB # 파일 하나의 최대 용량

com.sponet.upload.path: C:/HK/PROJECT/upload/image # 파일 저장 경로